### ISSUE TITLE
Mysql spouse example test sometimes fails

### ISSUE THREAD

**Issue by feiranwang** [HazyResearch/deepdive#350] opened 2015-08-10 08:19 UTC
As stated in the title. Looking into it.

**Comment by netj** [comment] 2015-08-24 18:26
For the record, our current guess of the cause is having different extractor implementations for mysql.  However, for the moment, let's just retry the test once more when it fails to suppress false alarms from Travis because that's basically what we're currently doing anyway.  We should get to the bottom of this and unify the underlying code eventually.

**Comment by netj** [comment] 2016-07-07 17:26
Closing as MySQL tests were dropped since nobody's seriously using it.

**Closed by netj** 2016-07-07 17:26 UTC
Labels: wontfix
