### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by skprasadu** [HazyResearch/deepdive#469] opened 2016-01-28 03:06 UTC
Hello,

When I am doing "sbt compile" I am getting a compilation error as below,

[error] /home/krishna/my-applications/java/deepdive/src/main/scala/org/deepdive/datastore/PostgresDataStore.scala:23: object dbcp is not a member of package org.apache.commons
[error]       val del = new org.apache.commons.dbcp.DelegatingConnection(connection)
[error]                                        ^
[error] one error found
[error] (compile:compile) Compilation failed

---

Can you see what is going on? Thanks in advance.

**Comment by netj** [comment] 2016-01-28 03:09
This is fixed in v0.7.x branch as 49c0bd478d22fc26ae4913c0add94ca3577311d7.  Duplicate of #443.

**Closed by netj** 2016-01-28 03:09 UTC
