### ISSUE TITLE
scala.reflect.internal.MissingRequirementError exception

### ISSUE THREAD

**Issue by profmocs** [HazyResearch/deepdive#596] opened 2016-09-25 01:41 UTC
I obtained the following exception running "deepdive do articles" on the spouse example. I used  articles-100.tsv.bz2.  Could someone tell me how to fix this? Thanks!

2016-09-24 21:35:36.565619 # on deepdive: deepdive do articles
2016-09-24 21:35:36.565723 # run/20160924/213533.976239671/plan.sh
2016-09-24 21:35:36.565739 # execution plan for data/articles
2016-09-24 21:35:36.565748 
2016-09-24 21:35:36.565756 ## process/init/app ##########################################################
2016-09-24 21:35:36.565765 # Done: N/A
2016-09-24 21:35:36.565773 process/init/app/run.sh
2016-09-24 21:35:36.565782 ++ dirname process/init/app/run.sh
2016-09-24 21:35:36.565790 + cd process/init/app
2016-09-24 21:35:36.565799 + export DEEPDIVE_CURRENT_PROCESS_NAME=process/init/app
2016-09-24 21:35:36.565807 + DEEPDIVE_CURRENT_PROCESS_NAME=process/init/app
2016-09-24 21:35:36.565815 + deepdive db init
2016-09-24 21:35:36.978169 + cd /root/spouse_example-0.8-STABLE
2016-09-24 21:35:36.978226 + [[ -r schema.sql ]]
2016-09-24 21:35:36.978237 + [[ -x input/init.sh ]]
2016-09-24 21:35:36.978245 + input/init.sh
2016-09-24 21:35:36.981813 Setting up Bazaar/Parser
2016-09-24 21:35:36.985019 Skipping download: /root/spouse_example-0.8-STABLE/udf/bazaar/parser/lib/stanford-srparser-2014-10-23-models.jar already exists
2016-09-24 21:35:41.315741 [info] Loading project definition from /root/spouse_example-0.8-STABLE/udf/bazaar/parser/project
2016-09-24 21:35:42.952259 [info] Set current project to deepdive-nlp-parser (in build file:/root/spouse_example-0.8-STABLE/udf/bazaar/parser/)
2016-09-24 21:35:43.470411 [info] Compiling 6 Scala sources to /root/spouse_example-0.8-STABLE/udf/bazaar/parser/target/scala-2.10/classes...
2016-09-24 21:35:44.629575 [error] error while loading <root>, error in opening zip file
2016-09-24 21:35:44.674646 scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
2016-09-24 21:35:44.674713 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
2016-09-24 21:35:44.674724 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
2016-09-24 21:35:44.674733 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
2016-09-24 21:35:44.674741 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
2016-09-24 21:35:44.674749 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
2016-09-24 21:35:44.674757 	at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:172)
2016-09-24 21:35:44.674765 	at scala.reflect.internal.Mirrors$RootsBase.getRequiredPackage(Mirrors.scala:175)
2016-09-24 21:35:44.674773 	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage$lzycompute(Definitions.scala:183)
2016-09-24 21:35:44.674780 	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage(Definitions.scala:183)
2016-09-24 21:35:44.674788 	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass$lzycompute(Definitions.scala:184)
2016-09-24 21:35:44.674796 	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass(Definitions.scala:184)
2016-09-24 21:35:44.674804 	at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr$lzycompute(Definitions.scala:1024)
2016-09-24 21:35:44.674812 	at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr(Definitions.scala:1023)
2016-09-24 21:35:44.674820 	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses$lzycompute(Definitions.scala:1153)
2016-09-24 21:35:44.674828 	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses(Definitions.scala:1152)
2016-09-24 21:35:44.674836 	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1196)
2016-09-24 21:35:44.674844 	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1196)
2016-09-24 21:35:44.674851 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1261)
2016-09-24 21:35:44.674859 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
2016-09-24 21:35:44.674867 	at xsbt.CachedCompiler0$$anon$2.<init>(CompilerInterface.scala:106)
2016-09-24 21:35:44.674875 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:106)
2016-09-24 21:35:44.674883 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
2016-09-24 21:35:44.674890 	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
2016-09-24 21:35:44.674898 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-09-24 21:35:44.674906 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2016-09-24 21:35:44.674914 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-09-24 21:35:44.674922 	at java.lang.reflect.Method.invoke(Method.java:498)
2016-09-24 21:35:44.674930 	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
2016-09-24 21:35:44.674937 	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
2016-09-24 21:35:44.674945 	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
2016-09-24 21:35:44.674953 	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:51)
2016-09-24 21:35:44.674961 	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
2016-09-24 21:35:44.674968 	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
2016-09-24 21:35:44.674976 	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
2016-09-24 21:35:44.674984 	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:50)
2016-09-24 21:35:44.674992 	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
2016-09-24 21:35:44.675000 	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
2016-09-24 21:35:44.675008 	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
2016-09-24 21:35:44.675016 	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
2016-09-24 21:35:44.675024 	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
2016-09-24 21:35:44.675032 	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
2016-09-24 21:35:44.675039 	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
2016-09-24 21:35:44.675047 	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
2016-09-24 21:35:44.675055 	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
2016-09-24 21:35:44.675062 	at sbt.inc.Incremental$.compile(Incremental.scala:61)
2016-09-24 21:35:44.675070 	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
2016-09-24 21:35:44.675078 	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
2016-09-24 21:35:44.675086 	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
2016-09-24 21:35:44.675094 	at sbt.Compiler$.compile(Compiler.scala:128)
2016-09-24 21:35:44.675102 	at sbt.Compiler$.compile(Compiler.scala:114)
2016-09-24 21:35:44.675109 	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:814)
2016-09-24 21:35:44.675117 	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:805)
2016-09-24 21:35:44.675125 	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:803)
2016-09-24 21:35:44.675133 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
2016-09-24 21:35:44.675141 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
2016-09-24 21:35:44.675149 	at sbt.std.Transform$$anon$4.work(System.scala:63)
2016-09-24 21:35:44.675156 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
2016-09-24 21:35:44.675164 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
2016-09-24 21:35:44.675172 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
2016-09-24 21:35:44.675180 	at sbt.Execute.work(Execute.scala:235)
2016-09-24 21:35:44.675188 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
2016-09-24 21:35:44.675195 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
2016-09-24 21:35:44.675203 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
2016-09-24 21:35:44.675211 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
2016-09-24 21:35:44.675219 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2016-09-24 21:35:44.675227 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2016-09-24 21:35:44.675234 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2016-09-24 21:35:44.675242 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-09-24 21:35:44.675250 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-09-24 21:35:44.675258 	at java.lang.Thread.run(Thread.java:745)
2016-09-24 21:35:44.675266 [error] (compile:compileIncremental) scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
2016-09-24 21:35:44.680092 [error] Total time: 2 s, completed Sep 24, 2016 9:35:44 PM
‘run/ABORTED’ -> ‘20160924/213533.976239671’

**Comment by profmocs** [comment] 2016-09-25 01:42
I am running deepdive on Centos 7.

**Comment by netj** [comment] 2016-09-27 22:22
Sorry this is a long standing intermittent bug in sbt, required by our old CoreNLP wrapper, used by our spouse example.  Please retry after removing `~/.ivy2` and `~/.sbt`.  These kind of strange bugs will be gone once we merge #566.

Duplicate of #530

**Closed by netj** 2016-09-27 22:22 UTC
