### ISSUE TITLE
Need decent way to specify PG schema than error-prone PGOPTIONS

### ISSUE THREAD

**Issue by alldefector** [HazyResearch/deepdive#598] opened 2016-09-28 21:57 UTC
Ideally we shouldn't use binaries like `psql`, `createdb` at all. But even as we continue to use those, there is probably a better way to the unreliable and cumbersome `PGOPTIONS=-c search_path=xyz`.

**Comment by netj** [comment] 2016-11-02 02:12
Duplicate of #504

**Closed by netj** 2016-11-02 02:12 UTC
Labels: duplicate
