### ISSUE TITLE
Warn / report error on bad configuration

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#31] opened 2014-04-26 09:33 UTC
There should be error messages when encountering unexpected configuration items.

Just now I mistyped "dependencies" as "depencencies", and there is no error message on parsing the config file. Therefore the dependencies is broken but programmers do not know what cause the problem.

Strongly suggest that unexpected configs should be abandoned, or at least warned.

**Comment by netj** [comment] 2015-05-25 11:21
Duplicate of #1

**Closed by netj** 2015-05-25 11:21 UTC
Labels: enhancement
