### ISSUE TITLE
lower performance when sampling all variables vs just evidence variables

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#283] opened 2015-05-13 06:02 UTC
There are some reports that the new version of the sampler which uses both query and evidence variables may yield worse results than the previous version which uses only evidence variables.

We want to
1. verify that this problem indeed exists by collecting one or more small examples that reproduce this
2. fully understand why this is happening
3. come with a plan to fix this (bug in sampler? increase number of iterations/samples? flag to switch?)

**Comment by raphaelhoffmann** [comment] 2015-05-13 23:31
Some experimentation on the spouse example. Here I'm keeping the factor graph fixed and also the parameters to the sampler (-l 300 -s 1 -i 500 --alpha 0.1). The question is hot the commit on April 29th to the sampler repo affects results.

After commit ca3e8d45ef1c1c7d8badd16f82eb02847118d744
INFERENCE CALIBRATION (QUERY BINS):
PROB BIN 0.0~0.1  -->  # 65023
PROB BIN 0.1~0.2  -->  # 11
PROB BIN 0.2~0.3  -->  # 7
PROB BIN 0.3~0.4  -->  # 8
PROB BIN 0.4~0.5  -->  # 10
PROB BIN 0.5~0.6  -->  # 8
PROB BIN 0.6~0.7  -->  # 6
PROB BIN 0.7~0.8  -->  # 10
PROB BIN 0.8~0.9  -->  # 14
PROB BIN 0.9~0.10  -->  # 5903

The previous commit eaeac6838ff03c9bccd42d32ea3a0bed3436aab6
INFERENCE CALIBRATION (QUERY BINS):
PROB BIN 0.0~0.1  -->  # 12350
PROB BIN 0.1~0.2  -->  # 2897
PROB BIN 0.2~0.3  -->  # 2064
PROB BIN 0.3~0.4  -->  # 2054
PROB BIN 0.4~0.5  -->  # 1856
PROB BIN 0.5~0.6  -->  # 2085
PROB BIN 0.6~0.7  -->  # 2490
PROB BIN 0.7~0.8  -->  # 3251
PROB BIN 0.8~0.9  -->  # 5695
PROB BIN 0.9~0.10  -->  # 36258

Not sure why these distributions look so different. Perhaps it is just because the parameters to the sampler have to be calibrated to account for sampling from more variables. Increase the -i, -l, -s parameters by 10x on the newer version of the sampler has little effect. However, increasing the regularization parameter to -b 10 gives us

After commit ca3... with -b 10
INFERENCE CALIBRATION (QUERY BINS):
PROB BIN 0.0~0.1  -->  # 29013
PROB BIN 0.1~0.2  -->  # 3185
PROB BIN 0.2~0.3  -->  # 2707
PROB BIN 0.3~0.4  -->  # 2438
PROB BIN 0.4~0.5  -->  # 2205
PROB BIN 0.5~0.6  -->  # 2155
PROB BIN 0.6~0.7  -->  # 2030
PROB BIN 0.7~0.8  -->  # 2289
PROB BIN 0.8~0.9  -->  # 2373
PROB BIN 0.9~0.10  -->  # 22605

Is it possible that the regularization parameter is not calibrated correctly in the latest version?

**Comment by feiranwang** [comment] 2015-05-14 01:02
Partial results: the weights do not look correct. There are very large weights (~30) and very small weights (~-30).

**Comment by raphaelhoffmann** [comment] 2015-05-14 01:39
Hey Feiran,
I just added a few more results on variance which might help with debugging:
https://github.com/HazyResearch/deepdive/issues/282
Raphael

**Comment by feiranwang** [comment] 2015-05-14 03:24
@raphaelhoffmann Thanks! That's helpful. I also observed similar issues with the new sampler. I'll start from debugging logistic regression (without symmetry rule).

**Comment by chrismre** [comment] 2015-05-24 18:01
Is this closed?

**Comment by feiranwang** [comment] 2015-05-26 18:01
Using a smaller step size we can get similar distributions as before. @zhangce do you think this is still an issue?

**Comment by netj** [comment] 2015-06-17 18:56
Because of this issue, @feiranwang introduced the `--learn_non_evidence` option for the 0.6.0 release, turned off by default, to prevent users from seeing a sudden drop in their quality.  We should fix the quality issue in the correct approach and get rid of the option in the next release.

**Comment by netj** [comment] 2016-07-06 01:29
I believe the quality issue has been resolved by a bugfix in https://github.com/HazyResearch/sampler/commit/5347483558bfa7286f41050c5e536bb2e1945cc9

**Closed by netj** 2016-07-06 01:29 UTC
