### ISSUE TITLE
deepdive run with ddlog is not idempotent

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#412] opened 2015-09-26 02:22 UTC
Suppose you have a ddlog program with the following structure:
```
table1(
...
)
function f over () returns ... implementation ...
table1 += f(...) :- ...
```

Running ```deepdive run``` multiple times is not idempotent on such programs. More rows will be appended to table1 in each run.

Is there a way to overwrite or clear the tables? Using '=' instead of '+=' throws a compiler error.

**Comment by netj** [comment] 2015-09-26 15:29
There's no way yet.  I agree `deepdive run` should be idempotent.  I think the semantics of ddlog programs should be defined as starting from a state where all intensional relations are empty.  We could try to detect which relations are intensional vs. extensional, i.e. defined by ddlog vs. whose data come from external sources, or provide a syntax (or just annotation?) and truncate all intensional relations upon every run.

If there aren't use cases for running multiple functions to fill up one relation, e.g., `table1 += f(...) :- ... .  table1 += g(...) :- ... .`, then we could simply truncate (or drop/create) the output table for running functions for the moment and fully expand this EDB/IDB distinction later.  @feiranwang How does this sound?

**Comment by chrismre** [comment] 2015-09-26 15:53
There should be a mode to warn if you are going to drop data. We should
*NEVER* drop extensional , user supplied data. *NEVER.*

Intensional relations should only be dropped in a "force" mode or something
(imo).

Chris

**Comment by raphaelhoffmann** [comment] 2015-09-26 16:00
We just need a simple way to re-run ```deepdive run```, for example after you made some changes to a udf.

In that case you need to reset the generated tables. However, you can't use ```deepdive initdb``` because it will clear the entire database. It is also tedious and error-prone to use ```deepdive sql``` because you can easily forget a table.

**Comment by chrismre** [comment] 2015-09-26 16:02
This is why we have incremental processing...

**Comment by zhangce** [comment] 2015-09-26 17:08
I think one possible view of this is that each DeepDive run should have its own schema inside a database instance (as in PG's terminology, it is just a group of table with names, the default schema is `public`)--every DD run creates a new schema inside a DB instance, but never deletes/alters the old schema (we can have some tools to help the user to clean old DD-created tables in those old schema, but that is users' choice) . In case that data in the old schema can be reused (e.g., `sentences` table), DeepDive manages that reuse (as part of the incremental process). The guarantee is that DeepDive is functional and immutable on the schemas created before the current run.

**Comment by alldefector** [comment] 2015-09-26 17:44
Love Ce's idea! Schema-level separation between user data and internal data also came up when we were designing a live-ingestion-and-processing system (which is of course incremental).

A stop gap might be some syntax like `table1 = f(...)` (as opposed to `table1 += f(...)`), which would clear the table before populating it.

**Comment by feiranwang** [comment] 2015-09-26 18:24
@raphaelhoffmann I think what you need is ddlog truncating the output tables before running the extractors, as we usually do in `deepdive.conf`. In that way, every `deepdive run` will produce the same output instead of accumulating results from previous runs.

**Comment by raphaelhoffmann** [comment] 2015-09-26 18:32
@feiranwang That's exactly right. I just a need a simple solution for the short term. Is there a way to ```truncate``` in ddlog?

I understand that this more imperative way doesn't fit well with the declarative of nature of datalog, but the same may be true for "+="...

**Comment by chrismre** [comment] 2015-09-26 18:36
Let be clear here. WE *CANNOT DELETE USER DATA. *:) It cannot happen. So
please make sure the default is that this truncation does *not *happen.

Chris

**Comment by chrismre** [comment] 2015-09-26 18:46
let me propose that we have a separate call to deepdive that drops the
tables @netj. Dropping tables does not seem like a feature that should be
in the language...

**Comment by raphaelhoffmann** [comment] 2015-09-29 01:44
Yes. Some command like ``deepdive clear`` which checks app.ddlog for all tables and then truncates each one would be handy. It might make sense to ask the user for confirmation.

**Comment by ajratner** [comment] 2015-09-29 02:27
Isn't this similar to a (slightly more simple-minded) issue I posted which seems to have been partly resolved: #351 ?

To chime in with my now tedious "one time at band camp"-style comments... One time at genomics camp, we also implemented a short term fix for this issue which was to have two versions of the "initdb" command equivalent, one which did and one which did not ever touch user data (again, see my comments in #351 )

Again, it was also simpler to have a TRUNCATE script run as a "before" command for every extractor in the pre-ddlog syntax

In my tables code in ddlog, I had a post-processing script which went through the ddlog-generated app.conf file, and added this before script command back in for every extractor...

**Comment by alldefector** [comment] 2015-10-05 22:18
@netj what do you think of @zhangce 's proposal above? We could specify the search_path (say `dd_run_0003, public`) at the connection level or in the DB connection string.

Encapsulating all the internal tables away from user data will be a great move. Benefits are manyfold:
- cleanness: easy to see what's input, what's output, and what's intermediate
- lower risk of losing user data
- more friendly for people developing DD in a scientific / iterative manner (preserve runs)
- more friendly for people developing multiple extractors against the same input (think 200GB sentences table in GP and five people writing / running extractors against it)

**Comment by raphaelhoffmann** [comment] 2015-10-07 00:26
To add to @alldefector's bullets: We now create one database per extractor,
because it takes too long to run multiple extractors at once and we need to keep all
intermediate output. Our problem now is loading the sentences table (264G, > 1h),
which we wouldn't have with schema support.

@netj @zhangce We did a bunch of experiments around @zhangce 's idea of using separate schemas,
and have a preliminary integration of schema support in DeepDive. Support for schemas
does require a few changes to the code base, so it would be great to discuss how we want
to proceed.

1. Specifying the search_path in the DB connection string only works with newer
   versions of Postgresql, not Greenplum. It is possible, however, to run SQL on GP:
   ```SET search_path TO dd_run_0003, public;```. Also note: Most RDBMSs have schema
   support, but not MySQL.

2. The connection pool used by DeepDive (DBCP 1.x) does not support schemas.
   Fortunately, it is easy to change the connection pool.

   In ```build.sbt``` I added a dependency to

   ```
   "org.apache.commons" % "commons-dbcp2" % "2.1.1"
   ```
   and in ```deepdive.conf``` I added 
   ```
   deepdive.db.default {
       poolFactoryName: "commons-dbcp2"
       ...
   }
   ```
   No other change was necessary for this.

3. We now need to create the schema when we run ```deepdive initdb```. I think we
   should not let this command drop and create the entire DB; it should
   just create a new schema for the next run. In ```util/deepdive-initdb```, I added
   ```
   deepdive-sql "CREATE SCHEMA $SCHEMA_NAME;"
   ```

4. Finally, we need to make sure that JDBC uses the schema when
   creating a connection. Unfortunately, the default search_path on
   the database (```ALTER DATABASE ... SET search_path = ...```)
   is ignored by JDBC, and it doesn't look like scalikejdbc supports
   schemas or SQL queries for connection initialization. As a workaround, 
   I am now setting the schema in ```JdbcDataStore```:
   ```
   def borrowConnection() : Connection = {
     val c = ConnectionPool.borrow()
     c.setSchema(SCHEMA_NAME)
     c
   }  
   ```

So, this this might not be the most elegant solution, but works. Any thoughts on whether we
want something like this and on how to make the integration better?

**Comment by raphaelhoffmann** [comment] 2015-10-07 03:48
I added a branch with all the necessary changes.
 
https://github.com/HazyResearch/deepdive/compare/84898b1c9b9337a64057c521def5008b34d8913f...schema_support

If you build this and then, in your DD app, run

```
export DEEPDIVE_SCHEMA=my
deepdive initdb
```

then all generated tables will be in schema ``my``. You can verify this in psql by running
```
SET search_path = my,public;
\d
```

**Comment by netj** [comment] 2015-10-07 03:56
Sounds great @raphaelhoffmann. Thanks for exploring. 

I think we should add a separate command or commands that create/enumerate/drop the schema or versions rather than overloading deepdive initdb.  We can discuss more on what operations are needed with versioning and at what granularity for completeness.

Not being able to support MySQL is okay. We just need to provide a graceful way in the driver. 

I wish we could completely drop the use of JDBC and have Scala rely on `deepdive-sql eval` command as well.  This would allow us to concentrate our effort.  Not confirmed how big this change would be.  I'm good if there's a workaround for this, but ssl validation support for example also requires extra code for JDBC.

**Comment by raphaelhoffmann** [comment] 2015-10-08 23:39
We are now using schemas for our DeepDive app. It works well, and saves us a lot of time.

If you have access to our [repo](https://github.com/HazyResearch/elementary-memex/blob/schema_support/escort/bin/run), you can see how we are now launching the extractors.

Separate commands for the schemas would be nice, but are not absolutely necessary.

Something that would be very useful though is a DDLOG annotation that marks a table as a *user table* which DeepDive should assume exists and not try to drop and re-create. That way DeepDive can follow the search path to select the table from a different schema during execution.

I absolutely agree about replacing JDBC with calls to "deepdive sql". Also, it doesn't make sense why we are using a connection pool, since we don't have many concurrent requests and it just adds complexity.

If JDBC was replaced with deepdive sql, no change to the scala code base would be necessary in order to support schemas, since "deepdive sql" observes the DB-level search_path.

@netj How difficult do you think it would be to replace JDBC?

**Comment by netj** [comment] 2015-10-09 09:15
@raphaelhoffmann Great to hear it's working!

You can in fact already invent your own annotation and use `ddlog export-schema`'s json output to figure out user's table.  However I agree we should decide on a fixed annotation recognized by the deepdive subcommand that begins a new schema, sets up the search path, and drops such tables to make it visible.  It seems you changed `deepdive initdb`'s semantics and added `createdb`, but I think it's better to keep `initdb` and add a separate command.  Moreover, this SCHEMA stuff is postgresql-specific, so it should go under the driver.  I'll have to put a little more thought into this.

Taking out JDBC seems to be more difficult than I first thought.  It's quite deeply rooted and many parts are entangled with it, especially tests are heavily tied to JDBC, and json_extractor, calibration plot, piggy_extractor are relying on fancy type introspection.  However, in almost all meaningful cases, we just need a count or boolean back, so I'd say it's desirable to get rid of JDBC.  Migrating some parts out of scala and dropping some features temporarily will make this easier.

**Closed** 2016-01-05 01:16 UTC
